In [6]:
from mxnet import nd

In [10]:
x = nd.arange(12)
print(x)
print(x.shape)
print(x.size)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>
(12,)
12


In [4]:
X = x.reshape((3,4))
print('X=',X)

('X=', 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>)


In [5]:
zero = nd.zeros((2, 3, 4))
print(zero)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>


In [19]:
ones = nd.ones((3, 4))
print(ones)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>


In [22]:
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print('Y=',Y)

('Y=', 
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>)


In [22]:
normal = nd.random.normal(0, 1, shape=(3, 4))
print(normal)


[[ 2.2122064   0.7740038   1.0434405   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>


## 运算

In [23]:
print(X+Y)


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>


In [26]:
print(X*Y)


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>


In [27]:
print(X/Y)


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>


## 广播机制

In [16]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
print('A=',A)
print('B=',B)
print(A+B)

('A=', 
[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>)
('B=', 
[[0. 1.]]
<NDArray 1x2 @cpu(0)>)

[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>


## 索引

In [17]:
print(X[1:3])


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>


In [18]:
X[1,2] = 999
print(X)


[[  0.   1.   2.   3.]
 [  4.   5. 999.   7.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>


In [20]:
X[1:2, :] = 88
print(X)


[[ 0.  1.  2.  3.]
 [88. 88. 88. 88.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


## 运算的内存开销

In [26]:
before = id(Y)
print(Y)
print(before)
Y = Y + X
print(id(Y))
id(Y) == before


[[  2.   4.  10.  12.]
 [265. 266. 267. 268.]
 [ 28.  30.  32.  34.]]
<NDArray 3x4 @cpu(0)>
139729739521744
139729697037968


False

In [28]:
Z = Y.zeros_like()
print(Z)
before = id(Z)
print(before)
Z[:] = X + Y
id(Z) == before


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>
139729697036432


True

In [29]:
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True

In [30]:
before = id(X)
X += Y
id(X) == before

True

## NDArray和NumPy相互变换

In [31]:
import numpy as np

P = np.ones((2, 3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [32]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [34]:
help(nd.elemwise_add)

Help on function elemwise_add:

elemwise_add(lhs=None, rhs=None, out=None, name=None, **kwargs)
    Adds arguments element-wise.
    
    The storage type of ``elemwise_add`` output depends on storage types of inputs
    
       - elemwise_add(row_sparse, row_sparse) = row_sparse
       - elemwise_add(csr, csr) = csr
       - elemwise_add(default, csr) = default
       - elemwise_add(csr, default) = default
       - elemwise_add(default, rsp) = default
       - elemwise_add(rsp, default) = default
       - otherwise, ``elemwise_add`` generates output with default storage
    
    
    
    Parameters
    ----------
    lhs : NDArray
        first input
    rhs : NDArray
        second input
    
    out : NDArray, optional
        The output NDArray to hold the result.
    
    Returns
    -------
    out : NDArray or list of NDArrays
        The output of this function.
    
    Example
    -------
    
    >>> x = mx.nd.array([1, 2, 3, 4])
    >>> y = mx.nd.array([1.1, 2.1, 3.1, 4.1]